task4
codered23/book-store pull request #4
Opened 2023-09-03 20:18 UTC by codered23

2023-09-04 17:51 UTC, aaananas commented
<img width="1599" alt="image" src="https://github.com/codered23/book-store/assets/81781479/818dff44-dcf3-48ad-86bb-4ac5e1231ede">

nothing changed((

2023-09-04 19:29 UTC, codered23 commented
Окей, я дуже сильно шось заплутав тут з тими мерджами і комітами, останній коміт вроді мав бути таким як треба але тут його відкрив і тепер взагалі нічого не зрозуміло.

2023-09-05 09:41 UTC, Rommelua requested changes
You should have all changes here 
![image](https://github.com/codered23/book-store/assets/20326858/be41ba1c-4646-4292-ac2b-724a7513b516)

2023-09-13 10:02 UTC, Rommelua requested changes

2023-09-13 10:02 UTC, Rommelua commented on src/main/java/com/example/bookstore/dto/CreateBookRequestDto.java
>      private String isbn;
can we have Null price or isbn?

2023-09-20 04:49 UTC, merged