problem task
codered23/book-store pull request #6
Opened 2023-10-11 16:39 UTC by codered23

2023-11-13 10:58 UTC, Sanderfuck requested changes

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/controller/AuthenticationController.java
> +    }
You can use @RequredArgsContructor for no need to write this constructor

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/dto/UserLoginRequestDto.java
> +}
You can init min number of characters

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/dto/UserRegistrationRequestDto.java
> +    private String password;
You can add more validation for email and password

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/dto/UserRegistrationRequestDto.java
> +    }
Why do you need this if you have @Data?

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/dto/UserRegistrationResponseDto.java
> +        return this.password;
You have @Data

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/model/Role.java
> +    }
Better write it in stack structure

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/model/User.java
> +    private boolean isDeleted = false;
Why you init fields here?

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/model/User.java
> +                .map(role -> new SimpleGrantedAuthority("ROLE_" + role.getName().toString()))
You can use constant for String and use .name() instead toString

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/repository/specifications/AuthorSpecificationProvider.java
> +             root.get("author").in(Arrays.stream(authors).toArray());
Use constant

2023-11-13 10:58 UTC, Sanderfuck commented on src/main/java/com/example/bookstore/security/SecurityConfig.java
> +                //.formLogin(withDefaults())
Commented code??

2023-11-13 17:44 UTC, codered23 commented on src/main/java/com/example/bookstore/model/User.java
> +    private boolean isDeleted = false;
Окей а де мені їх сетити? в дтошках?

2023-11-13 17:45 UTC, codered23 commented on src/main/java/com/example/bookstore/model/Role.java
> +    }
Не розумію про що йдеться

2023-11-27 19:06 UTC, sokimaaa commented on src/main/java/com/example/bookstore/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
prefer unchecked exceptions over checked

2023-11-27 19:15 UTC, sokimaaa commented on src/main/java/com/example/bookstore/security/SecurityConfig.java
> +                                .requestMatchers("/api/auth/**")
permit `/error` and swagger

2023-11-27 19:15 UTC, sokimaaa commented on src/main/java/com/example/bookstore/security/SecurityConfig.java
> +                //.formLogin(withDefaults())
remove redundant comment

2023-11-29 17:00 UTC, codered23 commented on src/main/resources/db/changelog/changes/05-insert-roles.sql
> +# VALUES ('USER'),
так воно в мене закоментоване бо вже створені ці ролі і вилітає помилка якщо я їх розкоментую, якщо я це видалю тоді людина яка собі відкриє проект і запустить в себе не зможе нормально заінсертити стандратртні ролі, хіба ні? можливо навіть помилка у неї вилетить бо немає таких ролей

2023-11-29 17:12 UTC, codered23 commented on src/main/java/com/example/bookstore/security/SecurityConfig.java
> +                                .requestMatchers("/api/auth/**")
"/swagger*/**" типу ось так свагер дозволити? а що за error? я просто шось не зрозумів

2023-11-30 09:35 UTC, Rommelua commented on src/main/java/com/example/bookstore/dto/UserRegistrationRequestDto.java
> +    private String email;
```suggestion
    @NotNull 
    @Email 
    private String email;
```

2023-12-05 13:10 UTC, kerrrusha approved these changes

2023-12-25 18:55 UTC, merged