added Category entity with all stuff, added email validation (optional)
codered23/book-store pull request #7
Opened 2024-01-23 22:02 UTC by codered23

2024-01-24 18:32 UTC, kerrrusha requested changes

2024-01-24 18:32 UTC, kerrrusha commented on src/main/java/com/example/bookstore/config/Config.java
> +@Configuration
why did you used this annotation for regular constants class? there's no sense in it
```suggestion
```

2024-01-24 18:32 UTC, kerrrusha commented on src/main/java/com/example/bookstore/config/Config.java
> +            = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
better create this constant right in single place where you use it
```suggestion
```

2024-01-24 18:32 UTC, kerrrusha commented on src/main/java/com/example/bookstore/config/Config.java
> +            + "*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
better create this constant right in single place where you use it
```suggestion
```

2024-01-24 18:32 UTC, kerrrusha commented on src/main/java/com/example/bookstore/config/Config.java
should be removed at all

2024-01-24 23:23 UTC, codered23 commented on src/main/java/com/example/bookstore/config/Config.java
окей з цим зрозуміло, таке ще питання про ці категорії виходить нам ж треба якось сетити категорії в книжку, то може б треба було створити якийсь ще метод для того щоб додати категорію до книги? чи це вирішиться в наступних завданнях? просто поки що ми можемо діставати книги по категорії але в нас всі книги не мають категорій))

2024-01-25 18:32 UTC, MentorMA approved these changes

2024-01-26 19:12 UTC, merged